[program:queue_one]
process_name=%(program_name)s
command=php /var/www/artisan queue:work rabbitmq --queue=queue_one --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/storage/logs/queue_one.worker.log
stopwaitsecs=3600
